v1_api:
    resource: ../../src/Controller/Api/V1
    prefix: /api/v1
    name_prefix: api.v1
    trailing_slash_on_root: true
    type: annotation
    defaults:
        _format: json

controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
