doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        driver: 'pdo_pgsql'
        server_version: '13.3'
        charset: utf8
#        default_table_options:
#            charset: utf8
#            collate: -
        types:
            pizza_id: 'App\Entity\Pizza\IdType'
            propery_id: 'App\Entity\Property\IdType'
            price_id: 'App\Entity\Price\IdType'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
